(package-ensure 'elfeed)
(require 'elfeed)

(setq elfeed-feeds
      '("https://www.chenshaowen.com/atom.xml"
        "https://wuchong.me/atom.xml"
        "https://coolshell.cn/feed"
        "http://www.skywind.me/blog/feed"
        "http://www.ruanyifeng.com/blog/atom.xml"
        "https://www.biaodianfu.com/feed"
        "http://www.wangtianyi.top/atom.xml"
        "http://www.zmonster.me/atom.xml"
        "https://linuxtoy.org/feeds/all.atom.xml"
        "https://lujun9972.github.io/rss.xml"
        "http://liqi.io/feed/"
        "https://bitinn.net/feed/"
        ;; "http://readhub.bayes.cafe/rss?channel=topics"
        "https://liuzhihang.com/atom.xml"
        "https://tech.meituan.com/feed/"
        "https://rsshub.app/zzz"
        ;; "https://www.infoq.cn/feed.xml"
        "http://feed.cnblogs.com/blog/u/236150/rss/"
        "http://jm.taobao.org/atom.xml"
        "http://luokangyuan.com/rss/"
        "https://www.wangfeng.pro/atom.xml"
        ;; "http://www.techweb.com.cn/rss/allnews.xml"
        ;; "http://www.ityouknow.com/feed.xml"
        "https://www.hollischuang.com/feed"
        ;; "http://www.justdojava.com/atom.xml"
        ;; "http://www.itwanger.com/feed.xml"
        "https://fookwood.com/feed"
        "http://www.jiangxinlingdu.com/feed.xml"
        "https://greatdk.com/feed"
        "https://blog.52itstyle.vip/feed/"
        "https://www.ffeeii.com/feed"
        ;; "https://feedpress.me/wx-ainlp"
        "https://feedpress.me/wx-catcoder"
        "https://feedpress.me/wx-latenews"
        "https://feedpress.me/wx-lxiaoshengmiao"
        "https://feedpress.me/wx-dreamytalks"
        "https://www.throwable.club/atom.xml"
        "https://www.ahoom.cn/feed/"
        "https://www.javaboy.org/atom.xml"
        ;; "http://blog.didispace.com/atom.xml"
        ;; "http://feeds.dzone.com/java"
        ;; "http://feeds.dzone.com/microservices"
        "https://www.yybxs.cn/feed"
        "http://www.54tianzhisheng.cn/atom.xml"
        "https://www.cnkirito.moe/atom.xml"
        "http://timd.cn/rss/"
        "https://brantou.github.io/atom.xml"
        "https://blog.joway.io/index.xml"
        "http://feed.cnblogs.com/blog/u/534487/rss/"
        ;; "https://blog.csdn.net/shenjian58/rss/list"
        "https://www.imtqy.com/feed"
        "http://ifeve.com/feed/"
        "https://blog.codinglabs.org/rss.xml"
        "http://blog.hacking.pub/rss/"
        "https://draveness.me/feed.xml"
        "http://www.leviathan.vip/atom.xml"
        "http://ningg.top/atom.xml"
        "https://harttle.land/feed.xml"
        "https://liutos.github.io/atom.xml"
        "https://reverland.org/archive.xml"
        ;; "https://blog.csdn.net/shenchaohao12321/rss/list"
        "https://www.yhspy.com/atom.xml"
        "https://blog.xgheaven.com/atom.xml"
        "http://einverne.github.io/feed.xml"
        "https://xiaozhou.net/atom.xml"
        "https://colobu.com/atom.xml"
        "https://dontpanic.blog/feed/"
        "https://www.sczyh30.com/atom.xml"
        "https://awen.me/atom.xml"
        "https://www.wenjinyu.me/atom.xml"
        "https://xcoder.in/atom.xml"
        "https://matt33.com/atom.xml"
        "https://tech.youzan.com/rss/"
        "http://feed.cnblogs.com/blog/u/534487/rss/"
        "https://leokongwq.github.io/atom.xml"
        "http://feeds.feedburner.com/cavendish"
        "https://10year.wordpress.com/feed/"
        "https://rsshub.app/blogs/wangyin"
        "https://taohuawu.club/rss.xml"))

(provide 'init-elfeed)
